<a href="https://colab.research.google.com/github/Ravindra1972/Anaytics-in-finance-using-Python/blob/main/DAY_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
#BINARY CLASSIFICATION

In [ ]:
df = pd.read_csv('/content/Underweight-knn.csv')
df

,Weight(x2),Height(y2),Class
0,51,167,Underweight
1,62,182,Normal
2,69,176,Normal
3,64,173,Normal
4,65,172,Normal
5,56,174,Underweight
6,58,169,Normal
7,57,173,Normal
8,55,170,Normal
9,53,171,Underweight


In [ ]:
x = df.iloc[:,[0,1]].values  #input values
x

array([[ 51, 167],
       [ 62, 182],
       [ 69, 176],
       [ 64, 173],
       [ 65, 172],
       [ 56, 174],
       [ 58, 169],
       [ 57, 173],
       [ 55, 170],
       [ 53, 171],
       [ 60, 184]])

In [ ]:
y = df.iloc[:,2].values  #output values
y

array(['Underweight', 'Normal', 'Normal', 'Normal', 'Normal',
       'Underweight', 'Normal', 'Normal', 'Normal', 'Underweight',
       'Underweight'], dtype=object)

In [ ]:
df.shape

(11, 3)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 3, metric = 'euclidean')

In [ ]:
model.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
#y_pred = model.predict([[57,170]])
#y_pred

array(['Normal'], dtype=object)

In [ ]:
model.score(x,y)*100

90.9090909090909

In [ ]:
#if value is less than 0.5     0(category)
#if value is more than 0.5,    1(category)
#TP
#TN
#FP
#FN

In [ ]:
y

array(['Underweight', 'Normal', 'Normal', 'Normal', 'Normal',
       'Underweight', 'Normal', 'Normal', 'Normal', 'Underweight',
       'Underweight'], dtype=object)

In [ ]:
y_pred1 = model.predict(x)
y_pred1

array(['Underweight', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal',
       'Normal', 'Normal', 'Normal', 'Underweight', 'Underweight'],
      dtype=object)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred1,y)

array([[7, 1],
       [0, 3]])

In [ ]:
#7-true positive         (positive - 1)
#3-true negative         (negative - 0)

#1-false positive
#0-false negative

In [ ]:
(7+3)/(7+1+0+3)

0.9090909090909091

In [ ]:
#IRIS DATSET

In [ ]:
!git clone https://github.com/arib168/data.git

Cloning into 'data'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 7 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.


In [ ]:
df = pd.read_csv('/content/Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [ ]:
df.describe()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,75.500000,5.843333,3.054000,3.758667,1.198667
std,43.445368,0.828066,0.433594,1.764420,0.763161
min,1.000000,4.300000,2.000000,1.000000,0.100000
25%,38.250000,5.100000,2.800000,1.600000,0.300000
50%,75.500000,5.800000,3.000000,4.350000,1.300000
75%,112.750000,6.400000,3.300000,5.100000,1.800000
max,150.000000,7.900000,4.400000,6.900000,2.500000


In [ ]:
x = df.iloc[:,[1,2,3,4]]
x

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [ ]:
y = df.iloc[:,5]
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [ ]:
#k=sqrt(150), we are considering k=13 because we take sqrt(150),
#here 150 is total no. of values in the dataset

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 7, metric = 'euclidean')

In [ ]:
model.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [ ]:
y_pred = model.predict([[6.7,3.0,5.2,2.3]])
y_pred

array(['Iris-virginica'], dtype=object)

In [ ]:
y_pred = model.predict([[4.6,3.1,1.5,0.2]])
y_pred

array(['Iris-setosa'], dtype=object)

In [ ]:
model.score(x,y)*100

97.33333333333334

In [ ]:
y_pred2 = model.predict(x)  #our model's prediction data
y_pred2

In [ ]:
y

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred2,y)

array([[50,  0,  0],
       [ 0, 47,  1],
       [ 0,  3, 49]])

In [ ]:
(50+47+49)/(50+47+1+3+49)

0.9733333333333334

In [ ]:
!pip install streamlit --quiet
!pip install pyngrok==4.1.1 --quiet
from pyngrok import ngrok

     |████████████████████████████████| 7.8MB 5.2MB/s 
     |████████████████████████████████| 81kB 8.6MB/s 
     |████████████████████████████████| 174kB 44.6MB/s 
     |████████████████████████████████| 112kB 42.2MB/s 
     |████████████████████████████████| 4.2MB 35.3MB/s 
     |████████████████████████████████| 71kB 7.8MB/s 
     |████████████████████████████████| 122kB 46.3MB/s 
ERROR: ipykernel 6.0.0 has requirement ipython>=7.23.1, but you'll have ipython 5.5.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement ipykernel~=4.10, but you'll have ipykernel 6.0.0 which is incompatible.


In [ ]:
%%writefile app.py
#magic command,   writefile creates a new file
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
import streamlit as st
import numpy as np
st.title('IRIS FLOWER CLASSIFICATION')
var = load_iris()
x = var.data  #inputs
y = var.target #outputs
model = KNeighborsClassifier(n_neighbors=13)
model.fit(x,y)
xmin = np.min(x, axis = 0) #min values of inputs to take all the features
xmax = np.max(x, axis =0)  #max values of input to take all the features

sepal_length = st.slider('Sepal Length',float(xmin[0]),float(xmax[0]))  # to set the proper range we use float(xmin) and float(xmax)
sepal_width = st.slider('Sepal width',float(xmin[1]),float(xmax[1]))
petal_length = st.slider('Petal Length',float(xmin[2]),float(xmax[2]))
petal_width = st.slider('Petal width',float(xmin[3]),float(xmax[3]))

y_pred = model.predict([[sepal_length,sepal_width,petal_length,petal_width]])
op = ['Setosa', 'Versicolor','Virginica']
st.title(op[y_pred[0]])  #we write 0 because the value will  be in 1 dimension

Overwriting app.py


In [ ]:
!nohup streamlit run app.py & #nohup and & makes sure that the web app keeps running continously in background

nohup: appending output to 'nohup.out'


In [ ]:
public_url = ngrok.connect(port = '8501')  #ngrok and streamlit, we use port number 8501 for streamlit
public_url

'http://a255ecfe9b17.ngrok.io'